### ISSUE TITLE
Copyright Clause

### ISSUE THREAD

**Issue by ghost** [gitpay/code-of-conduct#1]
Article I, Section 8, Clause 8 of the United States Constitution, known as the Copyright Clause, empowers the United States Congress:

To promote the Progress of Science and useful Arts, by securing for limited Times to Authors and Inventors the exclusive Right to their respective Writings and Discoveries.

source: https://en.wikipedia.org/wiki/Copyright_Clause 

It was unclear in the info how contributions may be considered both in the present, and the future.  The concept of copyright (or Intellectual property generally) may not bind-well to online, given that so much of online contribution is not easily attributed to traditional intellectual property law; however, notwithstanding, the idea of contribution should in-theory still maintain meaning and purpose, regardless of language - ie: french, italian, english, html, javascript,  ruby, python, image, video + audio, etc.

Translation therein becomes the subject of notation and innovation...

Example of future consideration may include;

Group assess contribution to be deemed a threat or discouraging.  In Future, the contribution is found to embody precedent of consideration in a manner that was not reflected by other associates at the time.

In the interests of the project, and its contributors, such considerations should shift in-line with time. https://en.wikipedia.org/wiki/Four-dimensional_space

**Comment by melvincarvalho** [comment]
Out of scope, at this time.
